### ISSUE TITLE
User Login/Auth

### ISSUE THREAD

**Issue by megangilpin** [megangilpin/finito#5]

**Comment by ryancbrown** [comment]
https://github.com/megangilpin/finito/tree/login-functional

Refactored login to include api routes. Fixed issues with client side post-submission erroring. On successful login, page now redirects to /dashboard, but does not render on the client other than in the URL as React routing has not been set up.

**Comment by ryancbrown** [comment]
Resolved in: https://app.zenhub.com/workspaces/arryvl-5d7d4ae946611c000130ccf0/issues/megangilpin/finito/11
